//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by expAOS.rc
//
#define IDD_EXPAOS_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDD_CT                          130
#define IDD_ZRNK                        132
#define IDD_DWFSPROP                    134
#define IDD_DVLT                        136
#define IDD_DSTAT                       138
#define IDC_BtnCnnctWFS                 1000
#define IDC_BtnWfsProp                  1000
#define IDC_BtnStartWFS                 1001
#define IDC_SCNTWFS                     1002
#define IDC_SSTSWFS                     1002
#define IDC_BtnOneWFS                   1003
#define IDC_BtnCloseWFS                 1004
#define IDC_BtnStopWFS                  1005
#define IDC_BtnSetExpWFS                1006
#define IDC_EDIT1                       1007
#define IDC_EEXPOS                      1007
#define IDC_ESDX                        1007
#define IDC_EDIT2                       1008
#define IDC_EWFSREFCNT                  1008
#define IDC_ESDY                        1008
#define IDC_BtnGeRefWFS                 1009
#define IDC_ESWND                       1009
#define IDC_SS                          1010
#define IDC_ELEFT                       1010
#define IDC_SWFSFPS                     1011
#define IDC_CT                          1012
#define IDC_BtnWFSLESCHOISE             1012
#define IDC_ETOP                        1012
#define IDC_ZRNK                        1013
#define IDC_BtnWFSLESCHOISESAVE         1013
#define IDC_BtnCnnctWFS2                1014
#define IDC_ESHFTCOL                    1015
#define IDC_BtnSetLMore                 1015
#define IDC_ESHFTROW                    1016
#define IDC_ELENI                       1016
#define IDC_ENORM                       1017
#define IDC_SSUB                        1017
#define IDC_BtnStartTTS                 1017
#define IDC_BtnGrab                     1018
#define IDC_LIST1                       1018
#define IDC_SMINX                       1019
#define IDC_SSTSTTS                     1019
#define IDC_ESUB                        1020
#define IDC_CNTGRAB                     1020
#define IDC_SCARX                       1020
#define IDC_ENGRID                      1021
#define IDC_SMINY                       1021
#define IDC_BtnOneTTS                   1021
#define IDC_SS2                         1022
#define IDC_ESUBTRUH                    1022
#define IDC_BtnSetExpTTS                1022
#define IDC_SMAXX                       1023
#define IDC_EEXPOSTTS                   1023
#define IDC_SMAXY                       1024
#define IDC_EWFSREFCNTTTS               1024
#define IDC_SS3                         1025
#define IDC_BtnGeRefTTS                 1025
#define IDC_ENLENS                      1026
#define IDC_SAVERX                      1026
#define IDC_BtnCnnctTTS                 1026
#define IDC_ESRASTR                     1027
#define IDC_SAVERY                      1027
#define IDC_BtnTtsProp                  1027
#define IDC_SS4                         1028
#define IDC_BtnStopTTS                  1028
#define IDC_ENPZRNK                     1029
#define IDC_SS5                         1029
#define IDC_SSTSANL                     1029
#define IDC_ETRESHLOW                   1030
#define IDC_SSUB2                       1030
#define IDC_STTSFPS                     1030
#define IDC_ETRESHHIGH                  1031
#define IDC_SS6                         1031
#define IDC_ESZELENS                    1032
#define IDC_SDISPX                      1032
#define IDC_STTSDX                      1032
#define IDC_EPIXSZE                     1033
#define IDC_SDISPY                      1033
#define IDC_SS27                        1033
#define IDC_ELWAVE                      1034
#define IDC_ESCL                        1034
#define IDC_SCARY                       1034
#define IDC_EFOCUSCAM                   1035
#define IDC_SS8                         1035
#define IDC_SDISPSUBX                   1035
#define IDC_ELPATH                      1036
#define IDC_SS7                         1036
#define IDC_EFON                        1036
#define IDC_ECOEFSHIFT                  1037
#define IDC_SCNX                        1037
#define IDC_STTSDY                      1037
#define IDC_SCNY                        1038
#define IDC_ENTRANCESUB                 1038
#define IDC_STTSUX                      1038
#define IDC_SS9                         1039
#define IDC_EDISTBET                    1039
#define IDC_SUTTS                       1039
#define IDC_SR0X                        1040
#define IDC_STTSUY                      1040
#define IDC_SR0Y                        1041
#define IDC_STTSRFFX                    1041
#define IDC_SS10                        1042
#define IDC_SS28                        1042
#define IDC_SS11                        1043
#define IDC_STTSRFFY                    1043
#define IDC_SS12                        1044
#define IDC_SS29                        1044
#define IDC_BtnWFSMirrConnect           1045
#define IDC_SS18                        1045
#define IDC_BtnWFSMirrShowGUI           1046
#define IDC_SS20                        1046
#define IDC_SNFO                        1047
#define IDC_SS19                        1047
#define IDC_SS13                        1048
#define IDC_SDISPSUBY                   1048
#define IDC_BtnCloseLoopWFS             1049
#define IDC_SSUBDIF                     1049
#define IDC_SS14                        1050
#define IDC_BSAVEZRNK                   1051
#define IDC_SS21                        1051
#define IDC_BGRABFO                     1052
#define IDC_SCNSUBX                     1052
#define IDC_EELK                        1053
#define IDC_SCNSUBY                     1053
#define IDC_SU0                         1054
#define IDC_SRSUBX                      1054
#define IDC_SS15                        1055
#define IDC_SRSUBY                      1055
#define IDC_SS16                        1056
#define IDC_SK1                         1056
#define IDC_BGRABFO2                    1057
#define IDC_BSETVLTTOE                  1057
#define IDC_SS22                        1057
#define IDC_ECOEF                       1058
#define IDC_SK2                         1058
#define IDC_EVLTG                       1059
#define IDC_SS23                        1059
#define IDC_SS17                        1060
#define IDC_SK3X                        1060
#define IDC_BSTATWFS                    1061
#define IDC_SS24                        1061
#define IDC_BFONEXT                     1062
#define IDC_SK3Y                        1062
#define IDC_BFOPREV                     1063
#define IDC_SS25                        1063
#define IDC_SC1                         1064
#define IDC_STTSMAX                     1064
#define IDC_SS26                        1065
#define IDC_STTSCTX                     1065
#define IDC_SC2                         1066
#define IDC_SS30                        1066
#define IDC_SC055                       1067
#define IDC_STTSCTY                     1067
#define IDC_STTSCORX                    1068
#define IDC_SS31                        1069
#define IDC_STTSCORY                    1070
#define IDC_STTSCORUX                   1071
#define IDC_SUTTS2                      1072
#define IDC_STTSCORUY                   1073
#define IDC_BSTATTTS                    1074
#define IDC_BtnCnnctANL                 1075
#define IDC_SANLFPS                     1076
#define IDC_SS32                        1077
#define IDC_BtnStartANL                 1078
#define IDC_BtnOneANL                   1079
#define IDC_BtnSetExpANL                1080
#define IDC_EEXPOSANL                   1081
#define IDC_EWFSREFCNTANL               1082
#define IDC_BtnGeRefANL                 1083
#define IDC_BtnStopANL                  1084
#define IDC_BtnANLProp                  1085
#define IDC_BSTATANL                    1086
#define IDC_ESCL2                       1087
#define IDC_ESCLTTS                     1087
#define IDC_SS33                        1088

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1050
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
